/**
 * Caddyfile generation.
 *
 * Deliberately small. Caddy is a large, well-documented server and this project
 * uses about six directives of it. Generating a minimal, readable Caddyfile
 * means someone can open it, understand exactly what is being served, and edit
 * it -- which matters, because a proxy you cannot inspect is a proxy you cannot
 * trust in front of your own application.
 */

/**
 * @param {object} cfg  A config from config.js
 * @param {object} [opts]
 * @param {number} [opts.httpPort]   Default 80.
 * @param {number} [opts.httpsPort]  Default 443.
 * @param {string} [opts.dataDir]    Where Caddy keeps its CA and certificates.
 * @returns {string}
 */
export function renderCaddyfile(cfg, opts = {}) {
  const { httpPort = 80, httpsPort = 443 } = opts;

  const lines = [];
  lines.push('# Generated by notlocalhost. Edit freely -- `up` will not overwrite');
  lines.push('# a Caddyfile you have changed unless you pass --force.');
  lines.push('#');
  lines.push(`# project: ${cfg.project}`);
  lines.push(`# domain:  ${cfg.domain}`);
  lines.push('');

  // Global options.
  lines.push('{');
  // The admin API is off by default: it is an unauthenticated control socket,
  // and nothing here needs it. Turning it on by accident would be worse than
  // anything this tool is trying to prevent.
  lines.push('\tadmin off');
  lines.push(`\thttp_port ${httpPort}`);
  lines.push(`\thttps_port ${httpsPort}`);
  // Issue certificates from Caddy's own local CA rather than a public one.
  // Nothing contacts an ACME server; this works entirely offline.
  lines.push('\tlocal_certs');
  // Caddy installs its own root into the platform trust store the first
  // time its internal issuer serves TLS. That puts a certificate authority
  // on the machine without anyone agreeing to it, and without this project
  // recording it -- so `down` neither knows to remove it nor could. Every
  // run left one behind, including every test that passed trust: false.
  //
  // Trust is installed by trustCa instead: only when the caller asked, and
  // only after the certificate is in the ledger. This line makes that the
  // only path by which a root reaches the store.
  lines.push(String.fromCharCode(9) + "skip_install_trust");
  lines.push('}');
  lines.push('');

  for (const site of cfg.sites) {
    lines.push(`${site.host} {`);
    lines.push('\ttls internal');
    lines.push(`\treverse_proxy ${site.upstream} {`);
    // Without this the upstream sees the proxy's own Host and generates URLs
    // for the wrong name -- which would break the very thing being tested.
    lines.push('\t\theader_up Host {upstream_hostport}');
    lines.push('\t\theader_up X-Forwarded-Host {host}');
    // The app must be told the request arrived over TLS, or a framework that
    // derives its own scheme will keep emitting http:// URLs and set cookies
    // without Secure, defeating the entire exercise.
    lines.push('\t\theader_up X-Forwarded-Proto https');
    lines.push('\t}');
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * A one-line summary of what the generated file will serve, for printing
 * before anything starts.
 */
export function summariseSites(cfg) {
  return cfg.sites.map((s) => `https://${s.host}  ->  ${s.upstream}`);
}

/**
 * Has the user edited the Caddyfile we generated?
 *
 * Comparing against a freshly rendered copy is enough: if it differs, someone
 * changed it, and overwriting their work without asking would be rude at best.
 */
export function isUnmodified(existing, cfg, opts) {
  if (typeof existing !== 'string') return true;
  const normalise = (s) => s.replace(/\r\n/g, '\n').trimEnd();
  return normalise(existing) === normalise(renderCaddyfile(cfg, opts));
}
